// let name;
// let person;

// name = 'pavit';
// person = name + 'CC14';

// alert(person);

let n = 54;

console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
console.log(n);
